### ISSUE TITLE
Exercise 1 screenshot

### ISSUE THREAD

**Issue by MattForshaw** [philipdarke/reproducible-actuarial-work#1]
In Exercise 1 we talk about the RStudio files pane, and then show the directory structure in the Windows file manager. I wonder if we should have that as either a screenshot of the RStudio file pane or a text-based depiction like the output of `tree`.

```
$ tree -L 1
.
├── README.md
├── TODO
├── cache
├── config
├── data
├── diagnostics
├── docs
├── dsthesa.Rproj
├── graphs
├── lib
├── logs
├── munge
├── profiling
├── reports
├── src
└── tests
```

**Comment by philipdarke** [comment]
Cheers Matt, agreed and updated with this

![projecttemplate](https://user-images.githubusercontent.com/43066442/53289405-8c94f700-378d-11e9-8080-0d7c99ae0abf.png)
